Repository eclipse-theia/theia-blueprint, pull requests merged in 2021-11, with the labels that each got.

#175 deps: bump `lerna` version
  lerna.json
  package.json
  yarn.lock
Labels: quality, security

#166 [CI] Replace decommissioned build.eclipse.org server in Jenkins config
  Jenkinsfile
  applications/electron/electron-builder.yml
  applications/electron/scripts/after-pack.js
  applications/electron/scripts/notarize.sh
  applications/electron/scripts/sign.sh
Labels: ci

#165 [Updater] Allow to inspect logs on error
  theia-extensions/theia-blueprint-updater/src/common/updater/theia-updater.ts
  theia-extensions/theia-blueprint-updater/src/electron-browser/updater/theia-updater-frontend-contribution.ts
  theia-extensions/theia-blueprint-updater/src/electron-main/update/theia-updater-impl.ts
Labels: electron
