Repository eclipse-theia/theia-blueprint, pull requests merged in 2021-08, with the labels that each got.

#133 ci: add `github actions` workflow
  .github/workflows/build.yml
Labels: ci

#131 electron: fix electron issues
  applications/electron/electron-builder.yml
  applications/electron/package.json
  theia-extensions/theia-blueprint-product/src/browser/theia-blueprint-frontend-module.ts
  theia-extensions/theia-blueprint-product/src/browser/theia-blueprint-getting-started-contribution.ts
  theia-extensions/theia-blueprint-product/src/node/theia-blueprint-backend-module.ts
  theia-extensions/theia-blueprint-product/src/node/theia-blueprint-variables-server.ts
  theia-extensions/theia-blueprint-updater/package.json
  theia-extensions/theia-blueprint-updater/src/electron-browser/theia-updater-frontend-module.ts
  theia-extensions/theia-blueprint-updater/src/electron-browser/updater/theia-updater-frontend-contribution.ts
  theia-extensions/theia-blueprint-updater/src/electron-main/update/theia-updater-impl.ts
  theia-extensions/theia-blueprint-updater/src/electron-main/update/theia-updater-main-module.ts
  yarn.lock
Labels: electron

#146 test: remove 'eclipse keymaps' from test
  applications/electron/test/app.spec.js
Labels: test

#142 Remove "Skip Mac CI signing" printout if not on Mac
  applications/electron/scripts/after-pack.js
Labels: ci

#143 [CI] Streamline project's CI
  .github/workflows/build.yml
  Jenkinsfile
Labels: enhancement, ci
